# Data overall analysis:For predicting 11 

1. opening batting ===>  batmans who have average more than 30-40 , with strike rate 150+
2. middle order    ===>  batting average 40+, with strike rate of 120+
3. finisher        ===>  strike rate 130+, 50+ 6s
4. spinner         ===> economie less than 6.5 and average less than 20
5. fatser          ===> economie less than 8.5 and average less than 20

# We will go for opening batsman in this segment

In [15]:
T20Ibat=pd.read_excel('D:\Dastats\Dream Big\Dream Big\T20Ibat.xlsx')

In [16]:
T20Ibat

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Column1
0,Mohammad Rizwan (PAK),2020-2023,69,60,14,2617,104*,56.89,2013,130,1,25,2,229,72,NaN
1,SA Yadav (IND),2021-2023,60,57,10,2141,117,45.55,1248,171.55,4,17,3,192,123,NaN
2,Babar Azam (PAK),2020-2023,68,62,6,2080,122,37.14,1612,129.03,3,18,5,232,33,NaN
3,JC Buttler (ENG),2020-2023,48,47,10,1667,101*,45.05,1112,149.91,1,15,3,161,70,NaN
4,N Pooran (WI),2020-2023,69,61,5,1499,82,26.76,1095,136.89,0,9,1,103,93,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,Sumon Khan (BAN),2023-2023,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN
430,Tanzim Hasan Sakib (BAN),2023-2023,2,-,-,-,-,-,-,-,-,-,-,-,-,NaN
431,Wafadar Momand (AFG),2023-2023,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN
432,KOK Williams (WI),2020-2020,2,-,-,-,-,-,-,-,-,-,-,-,-,NaN
433,Zahid Mahmood (PAK),2021-2021,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN

In [24]:
T20Ibat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 16 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Player   434 non-null    object
 1   Span     434 non-null    object
 2   Mat      434 non-null    int32
 3   Inns     434 non-null    int32
 4   NO       434 non-null    int32
 5   Runs     434 non-null    int32
 6   HS       434 non-null    object
 7   Ave      434 non-null    float64
 8   BF       434 non-null    int32
 9   SR       434 non-null    float64
 10  100      434 non-null    int32
 11  50       434 non-null    int32
 12  0        434 non-null    int32
 13  4s       434 non-null    int32
 14  6s       434 non-null    int32
 15  Column1  0 non-null      float64
dtypes: float64(3), int32(10), object(3)
memory usage: 37.4+ KB

In [19]:
T20Ibat['Ave'].replace('0.00',0,inplace=True)

In [22]:
T20Ibat.replace('-',0 , inplace=True)

In [23]:
T20Ibat['SR']=T20Ibat['SR'].astype('float')
T20Ibat['Ave']=T20Ibat['Ave'].astype('float')
T20Ibat['Mat']=T20Ibat['Mat'].astype('int')
T20Ibat['Inns']=T20Ibat['Inns'].astype('int')
T20Ibat['NO']=T20Ibat['NO'].astype('int')
T20Ibat['Runs']=T20Ibat['Runs'].astype('int')
T20Ibat['BF']=T20Ibat['BF'].astype('int')
T20Ibat['100']=T20Ibat['100'].astype('int')
T20Ibat['50']=T20Ibat['50'].astype('int')
T20Ibat['0']=T20Ibat['0'].astype('int')
T20Ibat['4s']=T20Ibat['4s'].astype('int')
T20Ibat['6s']=T20Ibat['6s'].astype('int')

# Deciding opners

In [25]:
condition1= (T20Ibat['Ave']>30) & (T20Ibat['SR']>150) & (T20Ibat['Mat'] > 10)

In [27]:
T20Ibat.loc[condition1]

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Column1
1,SA Yadav (IND),2021-2023,60,57,10,2141,117,45.55,1248,171.55,4,17,3,192,123,NaN
6,GD Phillips (NZ),2020-2023,55,49,8,1429,108,34.85,950,150.42,2,8,3,100,73,NaN
14,AK Markram (SA),2021-2023,37,33,6,1100,70,40.74,725,151.72,0,9,1,97,46,NaN
23,DA Miller (SA),2020-2023,44,39,16,959,106*,41.69,634,151.26,1,4,1,59,52,NaN
43,MP Stoinis (AUS),2020-2023,38,33,12,779,78,37.09,510,152.74,0,2,1,61,41,NaN
50,PD Salt (ENG),2022-2023,21,20,2,639,119,35.50,385,165.97,2,2,2,59,33,NaN
76,RR Rossouw (SA),2022-2023,14,13,2,440,109,40.00,243,181.06,2,1,3,40,27,NaN
78,YBK Jaiswal (IND),2023-2023,15,14,1,430,100,33.07,270,159.25,1,3,2,50,22,NaN
98,R Shepherd (WI),2020-2023,32,17,8,301,44*,33.44,197,152.79,0,0,2,10,25,NaN
108,RK Singh (IND),2023-2023,12,8,4,262,68*,65.50,145,180.68,0,1,0,26,14,NaN
140,Shoaib Malik (PAK),2020-2021,13,7,3,172,58*,43.00,114,150.87,0,2,1,10,8,NaN

# playing11
### In tis list only two opners are there so we are going with that thought....

## Opners=====>  'PD Salt (ENG)',    'YBK Jaiswal (IND)',

# Deciding middel order

In [28]:
condition2= (T20Ibat['Ave']>45) & (T20Ibat['SR']>130) & (T20Ibat['Mat'] > 10)
T20Ibat.loc[condition2]

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Column1
1,SA Yadav (IND),2021-2023,60,57,10,2141,117,45.55,1248,171.55,4,17,3,192,123,NaN
3,JC Buttler (ENG),2020-2023,48,47,10,1667,101*,45.05,1112,149.91,1,15,3,161,70,NaN
7,V Kohli (IND),2020-2022,38,36,10,1345,122*,51.73,981,137.10,1,13,2,108,44,NaN
94,RA Jadeja (IND),2020-2023,20,14,7,317,46*,45.28,218,145.41,0,0,0,29,9,NaN
108,RK Singh (IND),2023-2023,12,8,4,262,68*,65.50,145,180.68,0,1,0,26,14,NaN

### Jadeja is in all rounder category , so we will consider him in next segment....
### In middel order we will need player who can play solid to faster and spinners and who can hold the inning
### virat kohli ==> play both faster and spin , can provide holding
### JC Buttler ==> struggles against spin, but good hitter, can keep 
### SA Yadav  ==> play both fast & spin Well , 360 player can find gaps in middel over that what we want 
### RK Sing    ==> play both fast & spin Well , six hitting ability, pressure sustaing capacity

# middel order ===> V Kohli (IND)	, SA Yadav (IND) , JC Buttler (ENG)

In [30]:
T20Iallround=pd.read_excel('D:\Dastats\Dream Big\Dream Big\T20Iallround.xlsx')

In [33]:
T20Iallround.drop('Column1',axis=1,inplace = True)

In [39]:
T20Iallround.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Player    434 non-null    object
 1   Span      434 non-null    object
 2   Mat       434 non-null    int64
 3   Runs      434 non-null    object
 4   HS        434 non-null    object
 5   Bat Av    434 non-null    object
 6   100       434 non-null    object
 7   Wkts      434 non-null    object
 8   BBI       434 non-null    object
 9   Bowl Av   434 non-null    object
 10  5         434 non-null    object
 11  Ct        434 non-null    object
 12  St        434 non-null    object
 13  Ave Diff  434 non-null    object
dtypes: int64(1), object(13)
memory usage: 47.6+ KB

In [40]:
T20Iallround['Bat Av'].replace('0.00',0,inplace=True)
T20Iallround.replace('-',0 , inplace=True)

In [43]:
T20Iallround.columns

Index(['Player', 'Span', 'Mat', 'Runs', 'HS', 'Bat Av', '100', 'Wkts', 'BBI',
       'Bowl Av', '5', 'Ct', 'St', 'Ave Diff'],
      dtype='object')

In [47]:
T20Iallround['Bat Av']=T20Iallround['Bat Av'].astype('float')
T20Iallround['Mat']=T20Iallround['Mat'].astype('int')
T20Iallround['Wkts']=T20Iallround['Wkts'].astype('int')
T20Iallround['Runs']=T20Iallround['Runs'].astype('int')
T20Iallround['100']=T20Iallround['100'].astype('int')
T20Iallround['Bowl Av']=T20Iallround['Bowl Av'].astype('float')

In [52]:
condition3=  (T20Iallround['Wkts']>50) & (T20Iallround['Mat'] > 10)
T20Iallround.loc[condition3]

,Player,Span,Mat,Runs,HS,Bat Av,100,Wkts,BBI,Bowl Av,5,Ct,St,Ave Diff
70,PW Hasaranga (SL),2020-2023,48,462,71,13.58,0,77,4/9,15.63,0,18,0,-2.04
74,Shadab Khan (PAK),2020-2023,54,447,52,21.28,0,58,4/8,23.32,0,18,0,-2.04
89,MJ Santner (NZ),2020-2023,54,347,77*,18.26,0,56,4/16,23.39,0,23,0,-5.12
169,IS Sodhi (NZ),2020-2023,65,98,19,7.00,0,79,4/28,21.86,0,23,0,-14.86
192,TG Southee (NZ),2020-2023,51,68,8,8.50,0,72,5/25,20.68,1,31,0,-12.18
193,Haris Rauf (PAK),2020-2023,62,67,13*,6.70,0,83,4/18,21.71,0,17,0,-15.01
218,AU Rashid (ENG),2020-2023,64,50,22,5.00,0,68,4/2,24.97,0,19,0,-19.97
241,Arshdeep Singh (IND),2022-2023,42,34,12,8.50,0,59,4/37,20.91,0,12,0,-12.41
254,Mustafizur Rahman (BAN),2020-2023,51,28,9*,5.60,0,53,4/12,24.01,0,10,0,-18.41
263,A Zampa (AUS),2020-2023,47,26,13*,3.71,0,54,5/19,23.77,1,10,0,-20.06
315,T Shamsi (SA),2020-2023,49,10,4*,2.50,0,66,5/24,19.74,1,8,0,-17.24

In [54]:
T20Iallround.loc[T20Iallround['Player']=='RA Jadeja (IND)']

,Player,Span,Mat,Runs,HS,Bat Av,100,Wkts,BBI,Bowl Av,5,Ct,St,Ave Diff
94,RA Jadeja (IND),2020-2023,20,317,46*,45.28,0,18,3/15,22.94,0,5,0,22.34

In [35]:
T20Iball= pd.read_excel('D:\Dastats\Dream Big\Dream Big\T20Iball.xlsx')
T20Iball

,Player,Span,Mat,Inns,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR,4,5
0,Haris Rauf (PAK),2020-2023,62,60,224,1,1802,83,4/18,21.71,8.04,16.1,3,0
1,IS Sodhi (NZ),2020-2023,65,62,220.4,0,1727,79,4/28,21.86,7.82,16.7,3,0
2,PW Hasaranga (SL),2020-2023,48,47,179,1,1204,77,4/9,15.63,6.72,13.9,2,0
3,TG Southee (NZ),2020-2023,51,50,189.5,3,1489,72,5/25,20.68,7.84,15.8,1,1
4,AU Rashid (ENG),2020-2023,64,62,232.2,3,1698,68,4/2,24.97,7.3,20.5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,SA Yadav (IND),2021-2023,60,-,-,-,-,-,-,-,-,-,-,-
430,Yasir Ali (BAN),2022-2023,11,-,-,-,-,-,-,-,-,-,-,-
431,WA Young (NZ),2021-2023,14,-,-,-,-,-,-,-,-,-,-,-
432,Zakir Hasan (BAN),2023-2023,3,-,-,-,-,-,-,-,-,-,-,-
433,Zubaid Akbari (AFG),2023-2023,1,-,-,-,-,-,-,-,-,-,-,-

In [36]:
T20Iallround

,Player,Span,Mat,Runs,HS,Bat Av,100,Wkts,BBI,Bowl Av,5,Ct,St,Ave Diff
0,Mohammad Rizwan (PAK),2020-2023,69,2617,104*,56.89,1,-,-,-,-,40,9,-
1,SA Yadav (IND),2021-2023,60,2141,117,45.55,4,-,-,-,-,40,0,-
2,Babar Azam (PAK),2020-2023,68,2080,122,37.14,3,-,-,-,-,27,0,-
3,JC Buttler (ENG),2020-2023,48,1667,101*,45.05,1,-,-,-,-,42,7,-
4,N Pooran (WI),2020-2023,69,1499,82,26.76,0,-,-,-,-,39,7,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,CV Varun (IND),2021-2021,6,0,0,0.00,0,2,1/18,66.00,0,0,0,-65.99
430,Wafadar Momand (AFG),2023-2023,1,-,-,-,-,0,-,-,0,0,0,-
431,KOK Williams (WI),2020-2020,2,-,-,-,-,0,-,-,0,1,0,-
432,Zahid Mahmood (PAK),2021-2021,1,-,-,-,-,3,3/40,13.33,0,0,0,-
433,Zahir Khan (AFG),2023-2023,4,0,0,0.00,0,3,2/20,16.66,0,0,0,-16.66

In [55]:
T20Ibat

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Column1
0,Mohammad Rizwan (PAK),2020-2023,69,60,14,2617,104*,56.89,2013,130.00,1,25,2,229,72,NaN
1,SA Yadav (IND),2021-2023,60,57,10,2141,117,45.55,1248,171.55,4,17,3,192,123,NaN
2,Babar Azam (PAK),2020-2023,68,62,6,2080,122,37.14,1612,129.03,3,18,5,232,33,NaN
3,JC Buttler (ENG),2020-2023,48,47,10,1667,101*,45.05,1112,149.91,1,15,3,161,70,NaN
4,N Pooran (WI),2020-2023,69,61,5,1499,82,26.76,1095,136.89,0,9,1,103,93,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,Sumon Khan (BAN),2023-2023,1,0,0,0,0,0.00,0,0.00,0,0,0,0,0,NaN
430,Tanzim Hasan Sakib (BAN),2023-2023,2,0,0,0,0,0.00,0,0.00,0,0,0,0,0,NaN
431,Wafadar Momand (AFG),2023-2023,1,0,0,0,0,0.00,0,0.00,0,0,0,0,0,NaN
432,KOK Williams (WI),2020-2020,2,0,0,0,0,0.00,0,0.00,0,0,0,0,0,NaN
433,Zahid Mahmood (PAK),2021-2021,1,0,0,0,0,0.00,0,0.00,0,0,0,0,0,NaN

In [68]:
df=T20Ibat.merge(T20Iball, on='Player',how='outer')
df

,Player,Span_x,Mat_x,Inns_x,NO,Runs_x,HS,Ave_x,BF,SR_x,...,Overs,Mdns,Runs_y,Wkts,BBI,Ave_y,Econ,SR_y,4,5
0,Mohammad Rizwan (PAK),2020-2023,69,60,14,2617,104*,56.89,2013,130.00,...,0.0,0,0,0,0,0.00,0.00,0.0,0,0
1,SA Yadav (IND),2021-2023,60,57,10,2141,117,45.55,1248,171.55,...,0.0,0,0,0,0,0.00,0.00,0.0,0,0
2,Babar Azam (PAK),2020-2023,68,62,6,2080,122,37.14,1612,129.03,...,0.0,0,0,0,0,0.00,0.00,0.0,0,0
3,JC Buttler (ENG),2020-2023,48,47,10,1667,101*,45.05,1112,149.91,...,0.0,0,0,0,0,0.00,0.00,0.0,0,0
4,N Pooran (WI),2020-2023,69,61,5,1499,82,26.76,1095,136.89,...,0.0,0,0,0,0,0.00,0.00,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,Sumon Khan (BAN),2023-2023,1,0,0,0,0,0.00,0,0.00,...,2.0,0,20,0,0,0.00,10.00,0.0,0,0
430,Tanzim Hasan Sakib (BAN),2023-2023,2,0,0,0,0,0.00,0,0.00,...,6.0,0,60,2,1/15,30.00,10.00,18.0,0,0
431,Wafadar Momand (AFG),2023-2023,1,0,0,0,0,0.00,0,0.00,...,2.1,0,30,0,0,0.00,13.84,0.0,0,0
432,KOK Williams (WI),2020-2020,2,0,0,0,0,0.00,0,0.00,...,5.0,0,81,0,0,0.00,16.20,0.0,0,0
433,Zahid Mahmood (PAK),2021-2021,1,0,0,0,0,0.00,0,0.00,...,4.0,0,40,3,3/40,13.33,10.00,8.0,0,0

In [69]:
df.columns

Index(['Player', 'Span_x', 'Mat_x', 'Inns_x', 'NO', 'Runs_x', 'HS', 'Ave_x',
       'BF', 'SR_x', '100', '50', '0', '4s', '6s', 'Column1', 'Span_y',
       'Mat_y', 'Inns_y', 'Overs', 'Mdns', 'Runs_y', 'Wkts', 'BBI', 'Ave_y',
       'Econ', 'SR_y', '4', '5'],
      dtype='object')

In [70]:
df1=df[['Player','Span_x','Mat_x','Inns_x','Runs_x','HS','Ave_x','SR_x','4s', '6s','Inns_y', 'Overs', 'Mdns', 'Runs_y', 'Wkts', 'BBI', 'Ave_y',
       'Econ', 'SR_y']]

In [71]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 434 entries, 0 to 433
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  434 non-null    object
 1   Span_x  434 non-null    object
 2   Mat_x   434 non-null    int32
 3   Inns_x  434 non-null    int32
 4   Runs_x  434 non-null    int32
 5   HS      434 non-null    object
 6   Ave_x   434 non-null    float64
 7   SR_x    434 non-null    float64
 8   4s      434 non-null    int32
 9   6s      434 non-null    int32
 10  Inns_y  434 non-null    int32
 11  Overs   434 non-null    float64
 12  Mdns    434 non-null    object
 13  Runs_y  434 non-null    int32
 14  Wkts    434 non-null    int32
 15  BBI     434 non-null    object
 16  Ave_y   434 non-null    float64
 17  Econ    434 non-null    float64
 18  SR_y    434 non-null    float64
dtypes: float64(6), int32(8), object(5)
memory usage: 54.2+ KB

In [66]:
T20Iball['Ave'].replace('0.00',0,inplace=True)
T20Iball.replace('-',0 , inplace=True)
T20Iball['SR']=T20Iball['SR'].astype('float')
T20Iball['Ave']=T20Iball['Ave'].astype('float')
T20Iball['Mat']=T20Iball['Mat'].astype('int')
T20Iball['Inns']=T20Iball['Inns'].astype('int')
T20Iball['Overs']=T20Iball['Overs'].astype('float')
T20Iball['Runs']=T20Iball['Runs'].astype('int')
T20Iball['Wkts']=T20Iball['Wkts'].astype('int')

T20Iball['Econ']=T20Iball['Econ'].astype('float')
T20Iball['4']=T20Iball['4'].astype('int')
T20Iball['5']=T20Iball['5'].astype('int')

In [67]:
T20Iball

,Player,Span,Mat,Inns,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR,4,5
0,Haris Rauf (PAK),2020-2023,62,60,224.0,1,1802,83,4/18,21.71,8.04,16.1,3,0
1,IS Sodhi (NZ),2020-2023,65,62,220.4,0,1727,79,4/28,21.86,7.82,16.7,3,0
2,PW Hasaranga (SL),2020-2023,48,47,179.0,1,1204,77,4/9,15.63,6.72,13.9,2,0
3,TG Southee (NZ),2020-2023,51,50,189.5,3,1489,72,5/25,20.68,7.84,15.8,1,1
4,AU Rashid (ENG),2020-2023,64,62,232.2,3,1698,68,4/2,24.97,7.30,20.5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,SA Yadav (IND),2021-2023,60,0,0.0,0,0,0,0,0.00,0.00,0.0,0,0
430,Yasir Ali (BAN),2022-2023,11,0,0.0,0,0,0,0,0.00,0.00,0.0,0,0
431,WA Young (NZ),2021-2023,14,0,0.0,0,0,0,0,0.00,0.00,0.0,0,0
432,Zakir Hasan (BAN),2023-2023,3,0,0.0,0,0,0,0,0.00,0.00,0.0,0,0
433,Zubaid Akbari (AFG),2023-2023,1,0,0.0,0,0,0,0,0.00,0.00,0.0,0,0

In [72]:
df1

,Player,Span_x,Mat_x,Inns_x,Runs_x,HS,Ave_x,SR_x,4s,6s,Inns_y,Overs,Mdns,Runs_y,Wkts,BBI,Ave_y,Econ,SR_y
0,Mohammad Rizwan (PAK),2020-2023,69,60,2617,104*,56.89,130.00,229,72,0,0.0,0,0,0,0,0.00,0.00,0.0
1,SA Yadav (IND),2021-2023,60,57,2141,117,45.55,171.55,192,123,0,0.0,0,0,0,0,0.00,0.00,0.0
2,Babar Azam (PAK),2020-2023,68,62,2080,122,37.14,129.03,232,33,0,0.0,0,0,0,0,0.00,0.00,0.0
3,JC Buttler (ENG),2020-2023,48,47,1667,101*,45.05,149.91,161,70,0,0.0,0,0,0,0,0.00,0.00,0.0
4,N Pooran (WI),2020-2023,69,61,1499,82,26.76,136.89,103,93,0,0.0,0,0,0,0,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,Sumon Khan (BAN),2023-2023,1,0,0,0,0.00,0.00,0,0,1,2.0,0,20,0,0,0.00,10.00,0.0
430,Tanzim Hasan Sakib (BAN),2023-2023,2,0,0,0,0.00,0.00,0,0,2,6.0,0,60,2,1/15,30.00,10.00,18.0
431,Wafadar Momand (AFG),2023-2023,1,0,0,0,0.00,0.00,0,0,1,2.1,0,30,0,0,0.00,13.84,0.0
432,KOK Williams (WI),2020-2020,2,0,0,0,0.00,0.00,0,0,2,5.0,0,81,0,0,0.00,16.20,0.0
433,Zahid Mahmood (PAK),2021-2021,1,0,0,0,0.00,0.00,0,0,1,4.0,0,40,3,3/40,13.33,10.00,8.0

In [82]:
condition4=  (df1['Econ']<6.50) & (df1['Mat_x'] > 10) & (df1['Econ']>0.00) & (df1['Overs']>30)&  (df1['Ave_y']<20)
df1.loc[condition4]

,Player,Span_x,Mat_x,Inns_x,Runs_x,HS,Ave_x,SR_x,4s,6s,Inns_y,Overs,Mdns,Runs_y,Wkts,BBI,Ave_y,Econ,SR_y
121,Rashid Khan (AFG),2020-2023,37,24,221,48*,15.78,136.41,14,14,37,141.2,0,873,46,4/9,18.97,6.17,18.4
131,AC Agar (AUS),2020-2022,26,21,195,27,11.47,100.51,13,6,26,98.4,0,609,31,6/30,19.64,6.17,19.0
163,MG Bracewell (NZ),2022-2023,16,11,113,61*,18.83,139.50,10,5,14,40.5,1,219,21,3/5,10.42,5.36,11.6
260,Kuldeep Yadav (IND),2021-2023,13,5,26,23*,8.66,66.66,0,0,13,44.5,1,264,19,5/17,13.89,5.88,14.1
390,JJ Bumrah (IND),2020-2023,18,1,0,0*,0.00,0.00,0,0,18,64.4,5,394,22,3/12,17.90,6.09,17.6

### we need 3 fast bowlers and 2 spinners

### JJ Bumrah (IND),Kuldeep Yadav (IND),Rashid Khan (AFG)

### we need 2 more fast bowlers

In [87]:
condition4=  (df1['Econ']<8.00) & (df1['Mat_x'] > 10) & (df1['Econ']>0.00) & (df1['Overs']>30)&  (df1['Ave_y']<20)
df1.loc[condition4]

,Player,Span_x,Mat_x,Inns_x,Runs_x,HS,Ave_x,SR_x,4s,6s,Inns_y,Overs,Mdns,Runs_y,Wkts,BBI,Ave_y,Econ,SR_y
70,PW Hasaranga (SL),2020-2023,48,41,462,71,13.58,124.86,48,8,47,179.0,1,1204,77,4/9,15.63,6.72,13.9
121,Rashid Khan (AFG),2020-2023,37,24,221,48*,15.78,136.41,14,14,37,141.2,0,873,46,4/9,18.97,6.17,18.4
126,Mosaddek Hossain (BAN),2021-2022,19,18,206,48*,17.16,122.61,16,6,14,33.3,1,238,13,5/20,18.30,7.10,15.4
131,AC Agar (AUS),2020-2022,26,21,195,27,11.47,100.51,13,6,26,98.4,0,609,31,6/30,19.64,6.17,19.0
163,MG Bracewell (NZ),2022-2023,16,11,113,61*,18.83,139.50,10,5,14,40.5,1,219,21,3/5,10.42,5.36,11.6
239,Usman Qadir (PAK),2020-2023,25,9,36,18*,9.00,120.00,3,1,21,72.0,0,573,31,4/13,18.48,7.95,13.9
260,Kuldeep Yadav (IND),2021-2023,13,5,26,23*,8.66,66.66,0,0,13,44.5,1,264,19,5/17,13.89,5.88,14.1
266,Mujeeb Ur Rahman (AFG),2020-2023,27,9,25,18,5.00,92.59,3,1,27,99.0,0,675,36,5/20,18.75,6.81,16.5
270,Ravi Bishnoi (IND),2022-2023,21,6,24,8*,6.00,171.42,2,1,21,82.4,0,591,34,4/16,17.38,7.14,14.5
277,JR Hazlewood (AUS),2020-2022,34,7,22,13*,11.00,157.14,2,1,34,125.4,4,912,50,4/12,18.24,7.25,15.0
294,A Nortje (SA),2020-2023,30,11,16,4*,2.66,47.05,1,0,29,100.5,0,715,38,4/10,18.81,7.09,15.9
315,T Shamsi (SA),2020-2023,49,11,10,4*,2.50,45.45,0,0,49,177.4,0,1303,66,5/24,19.74,7.33,16.1
390,JJ Bumrah (IND),2020-2023,18,1,0,0*,0.00,0.00,0,0,18,64.4,5,394,22,3/12,17.90,6.09,17.6


### so bowling lineup will be JJ Bumrah (IND),Kuldeep Yadav (IND),Rashid Khan (AFG), JR Hazlewood (AUS),A Nortje (SA)

## So it's time to get all rounder option

In [89]:
df1

,Player,Span_x,Mat_x,Inns_x,Runs_x,HS,Ave_x,SR_x,4s,6s,Inns_y,Overs,Mdns,Runs_y,Wkts,BBI,Ave_y,Econ,SR_y
0,Mohammad Rizwan (PAK),2020-2023,69,60,2617,104*,56.89,130.00,229,72,0,0.0,0,0,0,0,0.00,0.00,0.0
1,SA Yadav (IND),2021-2023,60,57,2141,117,45.55,171.55,192,123,0,0.0,0,0,0,0,0.00,0.00,0.0
2,Babar Azam (PAK),2020-2023,68,62,2080,122,37.14,129.03,232,33,0,0.0,0,0,0,0,0.00,0.00,0.0
3,JC Buttler (ENG),2020-2023,48,47,1667,101*,45.05,149.91,161,70,0,0.0,0,0,0,0,0.00,0.00,0.0
4,N Pooran (WI),2020-2023,69,61,1499,82,26.76,136.89,103,93,0,0.0,0,0,0,0,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,Sumon Khan (BAN),2023-2023,1,0,0,0,0.00,0.00,0,0,1,2.0,0,20,0,0,0.00,10.00,0.0
430,Tanzim Hasan Sakib (BAN),2023-2023,2,0,0,0,0.00,0.00,0,0,2,6.0,0,60,2,1/15,30.00,10.00,18.0
431,Wafadar Momand (AFG),2023-2023,1,0,0,0,0.00,0.00,0,0,1,2.1,0,30,0,0,0.00,13.84,0.0
432,KOK Williams (WI),2020-2020,2,0,0,0,0.00,0.00,0,0,2,5.0,0,81,0,0,0.00,16.20,0.0
433,Zahid Mahmood (PAK),2021-2021,1,0,0,0,0.00,0.00,0,0,1,4.0,0,40,3,3/40,13.33,10.00,8.0

In [92]:
condtion5=(df1['Econ']<8.00) & (df1['Mat_x'] > 10) & (T20Ibat['Ave']>30) & (T20Ibat['SR']>130) & (df1['Econ']>0.00) & (df1['Overs']>30)
df1.loc[condtion5]

,Player,Span_x,Mat_x,Inns_x,Runs_x,HS,Ave_x,SR_x,4s,6s,Inns_y,Overs,Mdns,Runs_y,Wkts,BBI,Ave_y,Econ,SR_y
20,HH Pandya (IND),2020-2023,52,46,1038,71*,30.52,137.66,78,50,42,122.0,0,974,35,4/16,27.82,7.98,20.9
66,KA Pollard (WI),2020-2022,33,25,511,75*,31.93,149.41,25,38,19,45.4,0,358,14,4/25,25.57,7.83,19.5
94,RA Jadeja (IND),2020-2023,20,14,317,46*,45.28,145.41,29,9,18,59.5,0,413,18,3/15,22.94,6.90,19.9

### so for allrounder place we got three players KA pollard is retire so we not thinking of him, we need allrounder who can finish the inning and have six hitting ablety and those things H pandya can do.

## The team till now is

## Opners=====> 'PD Salt (ENG)', 'YBK Jaiswal (IND)'

## middel order ===> V Kohli (IND) , SA Yadav (IND) , JC Buttler (ENG)

## bowlers====>JJ Bumrah (IND),Kuldeep Yadav (IND),Rashid Khan (AFG), JR Hazlewood (AUS),A Nortje (SA)Â¶

## all rounder===> HH Pandya (IND)

In [110]:
captain= pd.read_excel('D:\Dastats\Dream Big\Dream Big\captain data.xlsx')

In [124]:
players=['HH Pandya (IND)','JC Buttler (ENG)','V Kohli (IND)','Rashid Khan (AFG)']
captain[captain['Player'].isin(players)]

,Player,Span,Mat,Won,Lost,Tied,Draw,NR,W/L,%W,%L,% Tied,% Draw,%NR,%
13,V Kohli (IND),2017-2021,50,30,16,2,0,2,1.87,60.00,32.00,4.00,0,4.00,64.58
38,JC Buttler (ENG),2015-2023,31,16,14,0,0,1,1.14,51.61,45.16,0.00,0,3.22,53.33
99,HH Pandya (IND),2022-2023,16,10,5,1,0,0,2.00,62.50,31.25,6.25,0,0.00,65.62

## JC buttler can be captain because he has won t20I worldcup for his team, apart from winning ratio he will be captain

# Playing 11 Team for last 3 years

# PD Salt (ENG)
# YBK Jaiswal (IND)
# V Kohli (IND)
# JC Buttler (ENG)(WK)(C)
# SA Yadav (IND)
# HH Pandya (IND)
# Rashid Khan (AFG)
# Kuldeep Yadav (IND)
# JJ Bumrah (IND)
# JR Hazlewood (AUS)
# A Nortje (SA)